#' Apply standard formatting to fold change dataframe
#'
#' @param .data A dataframe containing fold change data generated by standard fold change calculation
#               should contain these standard columns "Analyte","FoldChange","log2Foldchange","statistic","p.value","method","alternative","p.value.original","p.value.adjustment.method","-log10pvalue"
#               group labels are inferred as first 2 columns that do not exist in standard set above
#' @param baselineLabel - string - group label used in the denominator for fold change
#' @param foldchangeStatistic - string - name of statistic used to calculate fold change - defaults to "median"
#' @return a user-firendly formatted data frame
#' @export
formatFoldChangeDataframe <- function(.data,baselineLabel,foldchangeStatistic="Median") {

  standardColumns <- c("Analyte","FoldChange","log2Foldchange","statistic","p.value","method","alternative","p.value.original","p.value.adjustment.method","-log10pvalue" )
  groupLabels <- str_split(setdiff(colnames(.data),standardColumns),' ', simplify = TRUE)[1:2]
  comparisonLabel <- groupLabels[which(groupLabels!=baselineLabel)]
  pValueAdjInd <- unique(.data$p.value.adjustment.method)!="none"

  .data <- .data %>%
    select(Analyte,
           FoldChange,
           p.value,
           "p-value (original)" = p.value.original,
           !!comparisonLabel,
           !!baselineLabel,
           "log<sub>2</sub> Fold Change" = `log2Foldchange`,
           "-log<sub>10</sub> p-value" = `-log10pvalue`,
           "Statistical test" = method,
           "Adjustment Method" = p.value.adjustment.method)

  colnames(.data)[which(colnames(.data)=="FoldChange")] <-  paste0("Fold Change (",comparisonLabel,"/",baselineLabel,")")
  colnames(.data)[which(colnames(.data)==baselineLabel)] <- paste0(baselineLabel," ",foldchangeStatistic)
  colnames(.data)[which(colnames(.data)==comparisonLabel)] <- paste0(comparisonLabel," ",foldchangeStatistic)
  colnames(.data)[which(colnames(.data)=="p.value")] <- ifelse(pValueAdjInd,"p-value (adj)","p-value")

  if(!pValueAdjInd) {
    # if no adjustment method was used, drop the adjustment columns
    .data$`p-value (original)` <- NULL
    .data$`Adjustment Method` <- NULL
  }

  return(.data)

}
